FROM debian:jessie                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        
ENV DEBIAN_FRONTEND noninteractive                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                        
RUN  apt-get update && \                                                                                                                                                                                                                                                
     apt-get install -y \                                                                                                                                                                                                                                               
       debootstrap && \                                                                                                                                                                                                                 
     rm -rf /var/lib/apt/lists/*                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        
# qemu-debootstrap --verbose --include=${kernel},locales,flash-kernel,sunxi-tools,apt,vim --arch=armhf jessie debian-jessie http://ftp.debian.org/debian                                                                                                                
                                                                                                                                                                                                                                                                        
# debootstrap --arch i386 sid debian-sid http://httpredir.debian.org/debian                                                                                                                                                                                             
# DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C chroot rootfs/ /debootstrap/debootstrap --second-stage                                                                                                                     
                                                                                                                                                                                                                                                                        
CMD ["/bin/bash"]
